version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/web
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - urynopol

  redis:
    image: bitnami/redis:7.0.5
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/redis.conf
      - ./redis/data:/bitnami/redis/data
    networks:
      - urynopol
    command: [ "redis-server", "/redis.conf" ]

  db:
    image: bitnami/postgresql:14-debian-11
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=inz
    ports:
      - 5432:5432

    networks:
      - urynopol
    volumes:
      - ./db_volume:/bitnami/postgresql

  reverse-proxy:
    image: nginx:1.23-alpine
    container_name: reverse_proxy
    depends_on:
      - app
    networks:
      - urynopol
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse_proxy/certs:/etc/nginx/ssl
    ports:
      - 443:443
      - 80:80

  email_service:
    build:
      context: ./
      dockerfile: ./email_service/Dockerfile
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - APP_ENV=prod
    networks:
      - urynopol

networks:
  urynopol:
    external: true
